### ISSUE TITLE
Fetaure request: display number of messages per chat

### ISSUE THREAD

**Issue by seyfro** [sintacs/sintacs-mwai-export-chats#2]
Thank you for your plugin – it has been extremely useful! I have a suggestion for an enhancement. Would it be possible to add a feature that displays not only the number of chats but also the number of messages per chat and the total number of messages? This additional information would be very helpful for our data analysis.

**Comment by sintacs** [comment]
@seyfro Hello, yes, this is possible. 
I could add a column to the table with the messages count per discussion / conversation.
To count the **total** number of messages, you have to iterate over all messages and deserialize the json. This could take a while, depending on the message count. 
Where should this number be displayed?

**Comment by seyfro** [comment]
that would be great. I guess next to the column messages would be good. And the sum of all messages could also be displayed next to the number of discussions on the paging section on top right of the table.

**Comment by sintacs** [comment]
I pushed an update with the changes.

**Comment by seyfro** [comment]
wow, thanks a lot - exactly what we need!
